application: webserverlist
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /getservers.php
  script: getservers.php

- url: /heartbeat.php
  script: heartbeat.php

- url: .*
  script: main.php
